name: canum-2018
channels:
  - gouarin
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib=2.1
  - scipy
  - splinart
  - nbconvert
  - ipywidgets
  - jupyter_contrib_nbextensions
  - imageio
  - pip:
    - nbgitpuller
    - autopep8
    - bookbook
    - imageio
    - pythreejs==1.0.0
    - pillow
