name: canum-2018
channels:
  - gouarin
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - tornado==4.5.3
  - tqdm
  - numpy
  - matplotlib=2.1
  - scipy
  - splinart
  - nbconvert
  - ipywidgets
  - imageio
  - seaborn
  - pip:
    - nbgitpuller
    - py-heat-magic
    - autopep8
    - bookbook
    - imageio
    - pythreejs==1.0.0
    - pillow
    - jupyter_contrib_nbextensions
