#!/bin/bash
git clone https://github.com/jupyter-widgets/pythreejs.git
cd pythreejs
pip install .

jupyter nbextension install --py --symlink --sys-prefix pythreejs --user
jupyter nbextension enable --py --sys-prefix pythreejs

jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter lab build